services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jeevansetu_backend
    restart: always
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      SQLITE_DB_PATH: /app/data/db.sqlite3
      ALLOWED_HOSTS: localhost,127.0.0.1,backend,frontend,host.docker.internal
      CORS_ALLOWED_ORIGINS: http://localhost,http://localhost:80,http://localhost:5173,http://127.0.0.1,http://127.0.0.1:5173
      CSRF_TRUSTED_ORIGINS: http://localhost,http://localhost:80,http://localhost:5173,http://127.0.0.1,http://127.0.0.1:5173
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
      - backend_media:/app/media
      - backend_static:/app/staticfiles

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jeevansetu_frontend
    restart: always
    ports:
      - "80:80"
      - "5173:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
  backend_media:
  backend_static:
