# Generated by Django 5.2.16 on 2026-10-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='disease',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any extra notes, disclaimers, or supplementary information.', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='causes',
            field=models.JSONField(blank=True, default=list, help_text='List of cause strings.'),
        ),
        migrations.AddField(
            model_name='disease',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Full overview / "What is this disease?" section.', null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention',
            field=models.JSONField(blank=True, default=list, help_text='List of prevention / healthy habit strings.'),
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_factors',
            field=models.JSONField(blank=True, default=list, help_text='List of risk factor strings or {"title":..., "description":...} objects.'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.JSONField(blank=True, default=list, help_text='List of common symptom strings.'),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment',
            field=models.JSONField(blank=True, default=list, help_text='Treatment / management information as a list of strings.'),
        ),
        migrations.AddField(
            model_name='disease',
            name='when_to_see_doctor',
            field=models.TextField(blank=True, help_text='When should the patient consult a doctor?', null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(help_text='Short description shown on disease list cards.'),
        ),
    ]
