export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  HOW_IT_WORKS: '/how-it-works',
  DISEASES: '/diseases',
  DISEASE_DETAILS: '/diseases/:id',
  CONTACT: '/contact',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  
  USER_DASHBOARD: '/dashboard',
  NEW_PREDICTION: '/prediction/new',
  PREDICTION_RESULT: '/prediction/result',
  PREDICTION_HISTORY: '/predictions',
  PREDICTION_DETAILS: '/predictions/:id',
  PROFILE: '/profile',
  CHANGE_PASSWORD: '/change-password',
  FEEDBACK: '/feedback',
  
  ADMIN_LOGIN: '/admin/login',
  ADMIN_VERIFY_OTP: '/admin/verify-otp',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_DETAILS: '/admin/users/:id',
  ADMIN_DISEASES: '/admin/diseases',
  ADMIN_SYMPTOMS: '/admin/symptoms',
  ADMIN_PREDICTIONS: '/admin/predictions',
  ADMIN_ML_MODELS: '/admin/ml-models',
  ADMIN_FEEDBACK: '/admin/feedback',
  ADMIN_ADMINS: '/admin/admins',
  ADMIN_ACTIVITY_LOGS: '/admin/activity-logs',
  ADMIN_SETTINGS: '/admin/settings',
};
