# Generated by Django 5.2.17 on 2026-09-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
